
Открыта страница about
"GET /about/ HTTP/1.1" 200 93
Открыта главная страница
"GET / HTTP/1.1" 200 99
Watching for file changes with StatReloader
Открыта главная страница
"GET / HTTP/1.1" 200 99
"GET /clients HTTP/1.1" 301 0
Открыта страница clients
"GET /clients/ HTTP/1.1" 200 180
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Открыта страница clients
Internal Server Error: /clients/
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 25, in clients
    return HttpResponse(**client)
           ^^^^^^^^^^^^^^^^^^^^^^
TypeError: django.http.response.HttpResponse() argument after ** must be a mapping, not QuerySet
"GET /clients/ HTTP/1.1" 500 64139
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Открыта страница clients
Internal Server Error: /clients/
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 25, in clients
    return HttpResponse(*client)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\http\response.py", line 374, in __init__
    super().__init__(*args, **kwargs)
TypeError: HttpResponseBase.__init__() takes from 1 to 6 positional arguments but 10 were given
"GET /clients/ HTTP/1.1" 500 68844
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Открыта страница clients
Internal Server Error: /clients/
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 27, in clients
    result = item.name_client + ' ' + item.phone_client + ' ' + item.email_client + ' ' + adress_client + '<br>'
                                                                                          ^^^^^^^^^^^^^
NameError: name 'adress_client' is not defined
"GET /clients/ HTTP/1.1" 500 64680
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Открыта страница clients
Internal Server Error: /clients/
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 27, in clients
    result += '<br>' + item.name_client + ' ' + item.phone_client + ' ' + item.email_client + ' ' + adress_client
                                                                                                    ^^^^^^^^^^^^^
NameError: name 'adress_client' is not defined
"GET /clients/ HTTP/1.1" 500 64756
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Открыта страница clients
"GET /clients/ HTTP/1.1" 200 461
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Открыта страница clients
"GET /clients/ HTTP/1.1" 200 592
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Открыта страница clients
"GET /clients/ HTTP/1.1" 200 592
Открыта страница product
Internal Server Error: /product/
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 36, in product
    result += '<br>' + item.name_product + ' ' + item.quantity_product + ' ' + item.price_product
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "int") to str
"GET /product/ HTTP/1.1" 500 64891
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Открыта страница product
"GET /product/ HTTP/1.1" 200 1026
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Открыта страница product
"GET /product/ HTTP/1.1" 200 1197
Открыта страница product
"GET /product/ HTTP/1.1" 200 1197
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Открыта страница product
"GET /product/ HTTP/1.1" 200 1216
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Открыта страница product
"GET /product/ HTTP/1.1" 200 1140
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Открыта страница order
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 45, in order
    result += '<br>' + item.client_order + ' ' + item.product_order + ' ' + item.price_order
              ~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "Client") to str
"GET /order/ HTTP/1.1" 500 63632
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Открыта страница order
"GET /order/ HTTP/1.1" 200 85
Watching for file changes with StatReloader
Открыта главная страница
"GET / HTTP/1.1" 200 99
Not Found: /sorting_orders_date/1
"GET /sorting_orders_date/1 HTTP/1.1" 404 3176
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /sorting_orders_date/1
"GET /sorting_orders_date/1 HTTP/1.1" 404 3176
Not Found: /sorting_orders_date/88
"GET /sorting_orders_date/88 HTTP/1.1" 404 3179
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /sorting_orders_date/88
"GET /sorting_orders_date/88 HTTP/1.1" 404 3179
D:\GB\Django\onlinestore\storeapp\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sorting_orders_date/88
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 57, in sorting_orders_date
    client = get_object_or_404(Client, pk=client_id)
             ^^^^^^^^^^^^^^^^^
NameError: name 'get_object_or_404' is not defined
"GET /sorting_orders_date/88 HTTP/1.1" 500 64260
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sorting_orders_date/88
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 61, in sorting_orders_date
    products = [product for order in orders for product in order.products.all()]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 61, in <listcomp>
    products = [product for order in orders for product in order.products.all()]
                                                           ^^^^^^^^^^^^^^
AttributeError: 'Order' object has no attribute 'products'
"GET /sorting_orders_date/88 HTTP/1.1" 500 68684
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sorting_orders_date/88
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 70, in sorting_orders_date
    return render(request, 'storeapp/sorting_orders_date', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: storeapp/sorting_orders_date
"GET /sorting_orders_date/88 HTTP/1.1" 500 79891
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sorting_orders_date/88
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 72, in sorting_orders_date
    return render(request, 'storeapp/sorting_orders_date', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: storeapp/sorting_orders_date
"GET /sorting_orders_date/88 HTTP/1.1" 500 79891
Watching for file changes with StatReloader
Internal Server Error: /sorting_orders_date/88
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 72, in sorting_orders_date
    return render(request, 'storeapp/sorting_orders_date', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: storeapp/sorting_orders_date
"GET /sorting_orders_date/88 HTTP/1.1" 500 79891
D:\GB\Django\onlinestore\onlinestore\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sorting_orders_date/88
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 72, in sorting_orders_date
    return render(request, 'storeapp/sorting_orders_date', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: storeapp/sorting_orders_date
"GET /sorting_orders_date/88 HTTP/1.1" 500 80285
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sorting_orders_date/88
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 73, in sorting_orders_date
    return render(request, 'storeapp/sorting_orders_date', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: storeapp/sorting_orders_date
"GET /sorting_orders_date/88 HTTP/1.1" 500 80278
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sorting_orders_date/88
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 73, in sorting_orders_date
    return render(request, 'storeapp/sorting_orders_date.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\defaulttags.py", line 241, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\defaulttags.py", line 478, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\urls\resolvers.py", line 848, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'order_products' not found. 'order_products' is not a valid view function or pattern name.
"GET /sorting_orders_date/88 HTTP/1.1" 500 172114
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sorting_orders_date/88
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 63, in sorting_orders_date
    products = [product for order in orders for product in order.products.all()]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 63, in <listcomp>
    products = [product for order in orders for product in order.products.all()]
                                                           ^^^^^^^^^^^^^^
AttributeError: 'Order' object has no attribute 'products'
"GET /sorting_orders_date/88 HTTP/1.1" 500 68955
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sorting_orders_date/88
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 73, in sorting_orders_date
    return render(request, 'storeapp/sorting_orders_date.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\defaulttags.py", line 241, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\defaulttags.py", line 478, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\urls\resolvers.py", line 848, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'order_products' not found. 'order_products' is not a valid view function or pattern name.
"GET /sorting_orders_date/88 HTTP/1.1" 500 172114
Internal Server Error: /sorting_orders_date/88
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 73, in sorting_orders_date
    return render(request, 'storeapp/sorting_orders_date.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\defaulttags.py", line 241, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\defaulttags.py", line 478, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\urls\resolvers.py", line 848, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'order_products' not found. 'order_products' is not a valid view function or pattern name.
"GET /sorting_orders_date/88 HTTP/1.1" 500 172173
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sorting_orders_date/88
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 74, in sorting_orders_date
    return render(request, 'storeapp/sorting_orders_date.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\defaulttags.py", line 241, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\template\defaulttags.py", line 478, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\urls\resolvers.py", line 848, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
"GET /sorting_orders_date/88 HTTP/1.1" 500 170888
"GET /sorting_orders_date/88 HTTP/1.1" 200 512
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /sorting_orders_date/88 HTTP/1.1" 200 521
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /sorting_orders_date/88 HTTP/1.1" 200 542
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sorting_orders_date/88
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 64, in sorting_orders_date
    products.append(product)
    ^^^^^^^^
NameError: name 'products' is not defined
"GET /sorting_orders_date/88 HTTP/1.1" 500 65056
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /sorting_orders_date/88 HTTP/1.1" 200 542
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sorting_orders_date/88
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 64, in sorting_orders_date
    products.append(*product)
TypeError: list.append() argument after * must be an iterable, not Product
"GET /sorting_orders_date/88 HTTP/1.1" 500 65340
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /sorting_orders_date/88 HTTP/1.1" 200 604
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /sorting_orders_date/88/30
"GET /sorting_orders_date/88/30 HTTP/1.1" 404 3209
D:\GB\Django\onlinestore\storeapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /sorting_orders_date/88/30 HTTP/1.1" 200 604
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /sorting_orders_date/88/30 HTTP/1.1" 200 604
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /sorting_orders_date/88/30
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 79, in sorting_orders_date
    context = sorting_orders_date_duration(duration)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 57, in sorting_orders_date_duration
    client = get_object_or_404(Client, pk=client_id)
                                          ^^^^^^^^^
NameError: name 'client_id' is not defined
"GET /sorting_orders_date/88/30 HTTP/1.1" 500 67476
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /sorting_orders_date/88/30 HTTP/1.1" 200 604
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\urls.py changed, reloading.
Watching for file changes with StatReloader
Открыта главная страница
"GET / HTTP/1.1" 200 99
Internal Server Error: /sorting_orders_date_year
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sorting_orders_date_year() missing 1 required positional argument: 'client_id'
"GET /sorting_orders_date_year HTTP/1.1" 500 60272
D:\GB\Django\onlinestore\storeapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /sorting_orders_date_year/88 HTTP/1.1" 200 604
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /sorting_orders_date_year/88 HTTP/1.1" 200 604
"GET /sorting_orders_date_year/88 HTTP/1.1" 200 612
"GET /sorting_orders_date/88/30 HTTP/1.1" 200 633
"GET /sorting_orders_date/88/9 HTTP/1.1" 200 632
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /sorting_orders_date/88/9 HTTP/1.1" 200 632
"GET /sorting_orders_date_year/88 HTTP/1.1" 200 612
D:\GB\Django\onlinestore\storeapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\onlinestore\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /sorting_orders_date/88/9 HTTP/1.1" 200 632
"GET /sorting_orders_date_year/88 HTTP/1.1" 200 612
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Открыта главная страница
"GET / HTTP/1.1" 200 99
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4052
"GET /products/add HTTP/1.1" 200 2015
Получили Наименование товара №4, Наименование товара задание №4, 100.0, 2, 2024-02-14, фото загружено
Internal Server Error: /products/add
Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: table storeapp_product has no column named image_product

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\onlinestore\storeapp\views.py", line 129, in product_form_add
    product.save()
  File "D:\GB\Django\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "D:\GB\Django\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\db\models\query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "D:\GB\Django\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\GB\Django\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\GB\Django\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\Django\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: table storeapp_product has no column named image_product
"POST /products/add HTTP/1.1" 500 151990
Watching for file changes with StatReloader
"GET /products/add HTTP/1.1" 200 2015
Получили Наименование товара №4, Наименование товара задание №4, 100.0, 2, 2024-02-14, фото загружено
"POST /products/add HTTP/1.1" 200 2106
Watching for file changes with StatReloader
Открыта главная страница
"GET / HTTP/1.1" 200 99
Watching for file changes with StatReloader
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/css/base.css HTTP/1.1" 200 21544
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
Watching for file changes with StatReloader
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 5944
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /admin/auth/group/ HTTP/1.1" 200 7783
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6811
"GET /static/admin/js/actions.js HTTP/1.1" 200 8067
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/core.js HTTP/1.1" 200 6208
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9042
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /admin/ HTTP/1.1" 200 5944
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 7538
"GET /admin/storeapp/client/ HTTP/1.1" 200 8576
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/storeapp/order/ HTTP/1.1" 200 8569
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/storeapp/product/ HTTP/1.1" 200 10117
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/storeapp/client/ HTTP/1.1" 200 8576
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/storeapp/client/add/ HTTP/1.1" 200 11736
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/css/forms.css HTTP/1.1" 200 9090
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
"POST /admin/storeapp/client/add/ HTTP/1.1" 200 12055
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/storeapp/client/add/ HTTP/1.1" 200 12055
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/storeapp/client/add/ HTTP/1.1" 200 12053
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/storeapp/client/add/ HTTP/1.1" 200 12055
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/storeapp/client/add/ HTTP/1.1" 200 11736
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/storeapp/client/add/ HTTP/1.1" 200 12055
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
D:\GB\Django\onlinestore\storeapp\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /admin/storeapp/client/ HTTP/1.1" 200 8576
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/storeapp/client/add/ HTTP/1.1" 200 11736
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/storeapp/client/add/ HTTP/1.1" 200 12059
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/storeapp/client/add/ HTTP/1.1" 200 12059
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/storeapp/client/add/ HTTP/1.1" 200 11736
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/storeapp/client/add/ HTTP/1.1" 200 12059
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
Watching for file changes with StatReloader
"GET /admin/storeapp/client/add/ HTTP/1.1" 200 11736
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/storeapp/client/add/ HTTP/1.1" 302 0
"GET /admin/storeapp/client/ HTTP/1.1" 200 10324
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /admin/storeapp/client/ HTTP/1.1" 200 10105
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/storeapp/client/1/change/ HTTP/1.1" 200 12072
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/storeapp/client/ HTTP/1.1" 200 10105
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4052
"GET /admin/auth/user/ HTTP/1.1" 200 13083
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"GET /admin/auth/group/add/ HTTP/1.1" 200 14066
"GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15492
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
"POST /admin/auth/group/add/ HTTP/1.1" 302 0
"GET /admin/auth/group/ HTTP/1.1" 200 10716
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/group/1/change/ HTTP/1.1" 200 14345
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/group/ HTTP/1.1" 200 10493
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/group/add/ HTTP/1.1" 200 14066
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/group/add/ HTTP/1.1" 302 0
"GET /admin/auth/group/add/ HTTP/1.1" 200 14363
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/group/ HTTP/1.1" 200 10835
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/group/2/change/ HTTP/1.1" 200 14356
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/group/2/change/ HTTP/1.1" 302 0
"GET /admin/auth/group/ HTTP/1.1" 200 11176
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/group/add/ HTTP/1.1" 200 14066
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/group/add/ HTTP/1.1" 302 0
"GET /admin/auth/group/ HTTP/1.1" 200 11542
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/group/add/ HTTP/1.1" 200 14066
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/group/add/ HTTP/1.1" 302 0
"GET /admin/auth/group/ HTTP/1.1" 200 11892
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/user/add/ HTTP/1.1" 200 12406
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/user/add/ HTTP/1.1" 302 0
"GET /admin/auth/user/2/change/ HTTP/1.1" 200 25196
"GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 14446
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
"GET /admin/auth/user/add/ HTTP/1.1" 200 12406
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/user/add/ HTTP/1.1" 302 0
"GET /admin/auth/user/3/change/ HTTP/1.1" 200 25196
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/user/3/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 14981
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/user/add/ HTTP/1.1" 200 12406
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/user/add/ HTTP/1.1" 302 0
"GET /admin/auth/user/4/change/ HTTP/1.1" 200 25196
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/user/4/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 15520
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/user/4/change/ HTTP/1.1" 200 24990
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/user/ HTTP/1.1" 200 15299
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/auth/user/ HTTP/1.1" 200 15299
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/ HTTP/1.1" 200 11317
"GET /admin/storeapp/product/ HTTP/1.1" 200 11691
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/storeapp/order/ HTTP/1.1" 200 8898
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/storeapp/client/ HTTP/1.1" 200 11292
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/storeapp/client/ HTTP/1.1" 200 12227
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/storeapp/order/ HTTP/1.1" 200 9885
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/storeapp/product/ HTTP/1.1" 200 12739
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/storeapp/product/1/change/ HTTP/1.1" 200 12700
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\GB\Django\onlinestore\storeapp\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/storeapp/product/1/change/ HTTP/1.1" 200 12895
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /static/admin/js/collapse.js HTTP/1.1" 200 1803
